### PR TITLE
Build process verified on 20.04.2 LTS

### PR DESCRIPTION
**Pull request by chrishobcroft**

### CODE REVIEW

**Comment by yondonfu** [comment]
Hey @chrishobcroft thanks for the PR!

IIRC you previously encountered some issues building from source on Ubuntu 20.04. Did you do anything differently this time around in order to successfully build from source on Ubuntu 20.04?

**Comment by chrishobcroft** [comment]
> IIRC you previously encountered some issues building from source on Ubuntu 20.04. Did you do anything differently this time around in order to successfully build from source on Ubuntu 20.04?

Yes, YRC! Back last year I was trying to get it built on 20.04 and it was failing due to some underlying library mismatch in the original release of 20.04. This time, I followed the new ["Build from source" docs at livepeer.org/docs](https://livepeer.org/docs/installation/install-livepeer#build-and-install), although I think that these are logically equivalent to the [old build docs](https://livepeer.org/docs/installation/install-livepeer#build-and-install).

One difference is that Ubuntu LTS version is now up to `20.04.2`, so I expect that it's more about Ubuntu updating libraries so that they work with `go-livepeer`.

Here is [a full transcript of the end-to-end build process](https://github.com/livepeer/livepeer-org/files/6261933/20.04.2.build.transcript.txt), on a clean-built `20.04.2` VPS, ending up with successful build, which passes all the `./test.sh` except the part that requires nvidia.

I did notice though, there is a slight niggle: the `./install_ffmpeg.sh` command needs to be run twice in order to succeed... it fails first time with `configure: error: Libnettle 3.6 was not found.` (at line `4649`). I don't know what's causing that, but `./install_ffmpeg.sh` succeeds second time, and then `make` works fine to create `livepeer` and `livepeer_cli`. It would seem from a quick eyeballing of the script, that it seems to reference `libnettle 3.7`, so perhaps there's something buried deep inside there that is still expecting `3.6`? But I have no clue why it's failing first time, but succeeding second time.

**Comment by yondonfu** [comment]
> I did notice though, there is a slight niggle: the ./install_ffmpeg.sh command needs to be run twice in order to succeed... it fails first time with configure: error: Libnettle 3.6 was not found. (at line 4649). I don't know what's causing that, but ./install_ffmpeg.sh succeeds second time, and then make works fine to create livepeer and livepeer_cli. 

Based on the build log you provided, it looks like the libnettle configure error is occurring when trying to install gnutls. But, then the second time the `install_ffmpeg.sh` script is run, it will see that the gnutls repo has already been cloned and won't bother trying to install gnutls again. But, the gnutls installation never completed the first time.

My best guess at the moment is that the second run of `install_ffmpeg.sh` skips the gnutls installation allowing it to complete and then `livepeer` can be run in broadcaster mode because the gnutls dependency is not used in that mode.

Did you try running `livepeer` in orchestrator/transcoder mode with Nvidia GPU transcoding? If this does not work then that would confirm my above theory that the gnutls installation never completed and that would only be a problem when running in orchestrator/transcoder mode with Nvidia GPU transcoding enabled.

**Comment by chrishobcroft** [comment]
Thank you for the response to this @yondonfu.

I don't currently have any Nvidia GPUs available to test the `livepeer` binary with.

But on the assumption that your analysis is correct, I will close this PR, and perhaps check the build process on future iterations of Ubuntu 20.x.

**Pull request closed without merging**
